### ISSUE TITLE
[bug]: useQueue

### ISSUE THREAD

**Issue by wmoooid** [siberiacancode/reactuse#119]
Писал тесты для useQueue и нашел баг:
Функция remove возвращает undefined вместо удаленного значения.

Текущая реализация: 
```
  const remove = () => {
    let removed;
    setQueue(([first, ...rest]) => {
      removed = first;
      return rest;
    });
    return removed as Value;
  };
```

Возможный фикс:
```
  const remove = () => {
    const [first, ...rest] = queue;
    setQueue(rest);
    return first;
  };
```

При такой реализации бага нет, но смущает, что берем очередь напрямую из стейта, а не из сетстейта. Что думаете?

**Comment by wmoooid** [comment]
Как вариант можно ещё что-то такое сделать:

```
  const remove = () => {
    setQueue(([, ...rest]) => rest);
    return queue[0];
  };
```

**Comment by debabin** [comment]
@wmoooid Забавный баг, с учетом того, что такая реализация у многих, баг понятен return выполняется первеe чем setState

Такая же бага https://github.com/uidotdev/usehooks/issues/276

**Comment by debabin** [comment]
Тут вероятнее всего такая же бага https://github.com/streamich/react-use/blob/master/src/useQueue.ts#L17

**Comment by debabin** [comment]
Все твои варианты с огрехом, если вызывать по 2 remove подряд, то получаем баг
![image](https://github.com/siberiacancode/reactuse/assets/45297354/f821a5b6-abe2-462a-bfec-5ee1ebf643de)

**Comment by debabin** [comment]
Залил фикс, прошу закрыть issue после проверки

**Comment by wmoooid** [comment]
Проверил, работает как надо
