### ISSUE TITLE
[feat]: Создать хук useBattery

### ISSUE THREAD

**Issue by debabin** [siberiacancode/reactuse#12]

**Comment by GorillaDevq** [comment]
@debabin Займу этот хук.
Доку под хуки никогда не писал)
Но посмотрю на примеры и нацарапаю:)

**Comment by debabin** [comment]
это причем задача не доку а именно хук

**Comment by GorillaDevq** [comment]
Да, я видел по описанию)
Ну, почему бы сразу с докой не накатать)

**Comment by debabin** [comment]
это будет супер круто

**Comment by GorillaDevq** [comment]
Хотел прикрепить пулреквест [#12](https://github.com/siberiacancode/reactuse/issues/12) и случайно отписался от issue
