### ISSUE TITLE
useBrowserLanguage & usePreferredLanguages

### ISSUE THREAD

**Issue by pPitohu** [siberiacancode/reactuse#162]
Точно ли необходимы два одинаковых (почти) хука:
[usePreferredLanguages](https://github.com/siberiacancode/reactuse/blob/main/src/hooks/usePreferredLanguages/usePreferredLanguages.ts)
[useBrowserLanguage](https://github.com/siberiacancode/reactuse/blob/main/src/hooks/useBrowserLanguage/useBrowserLanguage.ts)

Код у них в целом похож, и, для конечного пользователя, думаю, не составит труда достать из `usePreferredLanguages` первый элемент массива (основной язык). Я считаю, что хук `useBrowserLanguage` бесполезен.

**Comment by debabin** [comment]
Привет, а есть ли какая-то проблема существования этих двух хуков ? 
Данные хуки работают с разными полями из навигатора.

**Comment by debabin** [comment]
https://vueuse.org/core/usepreferredlanguages/
https://vueuse.org/core/useNavigatorLanguage/

В vueuse также существуют две реализации

**Comment by pPitohu** [comment]
Тут больше вопрос не в том, есть ли проблема в их существовании, а скорее необходимо ли существование двух хуков, выполняющих одинаковые действия?
Почему одинаковые? Потому что даже если просто зайти в доки, то четким текстом написано, что **первый элемент в списке `navigator.languages` _(используется в usePreferredLanguages)_ является ни чем иным, как `navigator.language` _(который используется в хуке useBrowserLanguage)_**, а подписка на событие `languagechange `происходит в обоих хуках

https://developer.mozilla.org/en-US/docs/Web/API/Navigator/languages

![image](https://github.com/siberiacancode/reactuse/assets/59769228/e1d26aa2-a441-487e-afbf-0ee6f1145971)
![image](https://github.com/siberiacancode/reactuse/assets/59769228/058d058f-dec6-47e7-829c-da1ae0c40c1d)

**Comment by pPitohu** [comment]
> https://vueuse.org/core/usepreferredlanguages/ https://vueuse.org/core/useNavigatorLanguage/
> 
> В vueuse также существуют две реализации

Во вью существует такая реализация, потому что там есть понятие реактивности, из-за чего, например, проще повесить `watch` на реактивный `navigator.language`, который будет единственной строкой, а не на целый массив всех языков.

**Comment by debabin** [comment]
Так твой аргумент работает и в сторону vueuse, у нас тоже значения из навигатора становятся реативными с помощью хука useSyncExternalStore, не вижу проблемы существования двух хуков, они не противоречат друг другу и их можно использовать вместе без проблем. Короче говоря конфликтов в этих хуках нет
