### ISSUE TITLE
Проблема с tree shaking

### ISSUE THREAD

**Issue by hywax** [siberiacancode/reactuse#173]
В проекте везде используется `import React from 'react';`, при билде в bundle будет записан весь react, даже функции, которые не используются. Чтобы правильно работал tree shaking, нужно делать import только необходимого функционала.

Приведу пример на [useBoolean](https://github.com/siberiacancode/reactuse/blob/main/src/hooks/useBoolean/useBoolean.ts)
```diff
- import React from 'react';
+ import { useState } from 'react';

/** The use boolean return type */
type UseBooleanReturn = [
  /** The current boolean state value */
  value: boolean,
  /** Function to toggle the boolean state */
  toggle: (value?: boolean) => void
];

/**
 * @name useBoolean
 * @description - Hook provides a boolean state and a function to toggle the boolean value
 *
 * @param {boolean} [initialValue=false] The initial boolean value
 * @returns {UseBooleanReturn} An object containing the boolean state value and utility functions to manipulate the state
 *
 * @example
 * const [on, toggle] = useBoolean()
 */
export const useBoolean = (initialValue = false): UseBooleanReturn => {
-  const [value, setValue] = React.useState(initialValue);
+  const [value, setValue] = useState(initialValue);
  const toggle = (value?: boolean) => setValue((prev) => value ?? !prev);

  return [value, toggle];
};
```
Не так давно слышал на стриме, что это "код стайл проекта", но это не правильно (выше писал, что bundle будет больше), а в чат не смог написать тк был таймаут 10 минут

**Comment by debabin** [comment]
Ну вообще вот тебе скриншоты, я переделал все компоненты, как ты описал и разницы нет (3кб это я лишний код удалил)
![image](https://github.com/siberiacancode/reactuse/assets/45297354/cb99d411-de8a-4368-8839-07c675c51ced)
![image](https://github.com/siberiacancode/reactuse/assets/45297354/6640a830-5207-45a4-a7ef-c5d66ece9b38)

**Comment by debabin** [comment]
Я даже специально оставил один хук и вот результат (оставил хук useBattery и менял импорт с import React, на import { useEffect, useState })
![image](https://github.com/siberiacancode/reactuse/assets/45297354/0fc69127-9c7b-4a0a-9bd5-c7d89fd381d8)
![image](https://github.com/siberiacancode/reactuse/assets/45297354/d2b0e9b7-6343-44b4-a5e0-2345df9bd838)

**Comment by hywax** [comment]
```
pnpm create vite my-react-app --template react
```
При билде получаем **143.36 kB**

Если добавляем reactuse, то получаем уже **171.59 kB**

При этом, если заменить импорт хотя бы в 1 функции на то, что я писал выше уже получаем **170.37 kB**.

Дело не в bundle библиотеки тк react в peerDependencies, а в весе проекта, где мы ее используем

**Comment by debabin** [comment]
![image](https://github.com/siberiacancode/reactuse/assets/45297354/872d368c-8d98-4f5d-bfc4-c73e4fb751e8)
![image](https://github.com/siberiacancode/reactuse/assets/45297354/d0f4bbeb-5855-4bec-b11f-6c4b4ef2ae13)

Ты можешь увидеть точно такой же код 1 в 1 от создателей reatom и effector, они в разы опытней чем я в этом вопросе, у них также просто делается `require('react')`

**Comment by hywax** [comment]
Ну в этом и есть загвоздка, что в проекте рабочий tree shaking, выкидывает не используемые части react, а если в коде будет `require("react")`, то он не будет выкидывать не используемые части тк импортится весь react.

**Comment by debabin** [comment]
Так я же тебе выше написал

1. так у всех и это логично, react нет в dependencies
2. попробуй собрать проект с React.useState или просто useState, бандл библиотеки будет 1 в 1, везде будет `require('react')`

Я просто проверил твое предложение, оно не работает

**Comment by hywax** [comment]
Надо смотреть esm сборку, а не cjs. Сейчас новые проекты все на esm

**Comment by debabin** [comment]
А вот ты похоже прав 

1. Это импорт useState, useEffect
![image](https://github.com/siberiacancode/reactuse/assets/45297354/9a9cf8b6-9c63-4f4e-90b1-73049ac1c1b9)

2. Это react импорт 
![image](https://github.com/siberiacancode/reactuse/assets/45297354/31962ba8-e2bd-48fa-be56-8415e73bc45c)

**Comment by hywax** [comment]
Tree shaking не работает с cjs и то, что в коде `require('react')` это нормально, так и должно быть. Но современные проекты все используют модули, а там уже надо испортить не весь react. Но если посмотреть esm то в билде будет `import i from"react"`, что неправильно

**Comment by debabin** [comment]
Вот так вот у эффектора @hywax 
![image](https://github.com/siberiacancode/reactuse/assets/45297354/9d702225-9893-4bb5-a498-5d02e86e9472)

**Comment by debabin** [comment]
Залил версию, можешь проверять @hywax
