### ISSUE TITLE
[test]: getDate tests error

### ISSUE THREAD

**Issue by zeroqs** [siberiacancode/reactuse#184]
@debabin  Падают тесты для getDate

rework tests - https://github.com/siberiacancode/reactuse/commit/9443bd4215157c413dc6271aff5208517c038ded

<img width="1232" alt="Снимок экрана 2024-06-25 в 21 02 46" src="https://github.com/siberiacancode/reactuse/assets/94167692/b1c0f851-c15e-412b-9009-07876f962d8a">

**Comment by debabin** [comment]
Забавный факт, чтобы пофиксить тесты ты сделал 7 -> 3, а другой человек сделал с 7 ->6, короче говоря все понятно виновата таймзона. Пофикшу сегодня тесты сам
