### ISSUE TITLE
[feat]: Create hook useTimer

### ISSUE THREAD

**Issue by debabin** [siberiacancode/reactuse#203]

**Comment by jantttez** [comment]
какой функционал должен быть в этом хуке, типо ретурн значения и нескольких экшенов для переключения ?

**Comment by debabin** [comment]
привет @jantttez, данный хук к сожалению занят специальным человеком, но данный хук это полный возврат все данных 

stop, start, pause, возрат времени + включить по умолчанию, чтобы таймер сразу шел, идет таймер или нет, будут использоваться хелперы с других хуков связанные со временем

**Comment by jantttez** [comment]
@debabin  понял.

**Comment by debabin** [comment]
@jantttez ты можешь взять другой хук из роудмапы
