### ISSUE TITLE
[bug]: debounce реализован с небольшим багом

### ISSUE THREAD

**Issue by loonlylokly** [siberiacancode/reactuse#230]
При использовании такого варианта реализации debounce теряется контекст, когда нужно использовать его с обработчиком событий. Вот пример: https://codepen.io/lonlylokly/pen/jOjKMXb (там нужно одну строку раскомментировать в js, а другую закомментировать и в консоле выведиться не input, а window . Я его взял из doka.guide , так как я сейчас исправляю там debounce https://github.com/doka-guide/content/pull/5493 ). Возможно он теряется ещё в каких-то ситуациях, но я не проверял.

Короче нужно контекст привязывать в функции которую передаем в setTimeout, или использовать function

**Comment by debabin** [comment]
https://github.com/siberiacancode/reactuse/pull/238 @loonlylokly
