### ISSUE TITLE
[feat]: Создать хук useMap

### ISSUE THREAD

**Issue by debabin** [siberiacancode/reactuse#46]

**Comment by dacorm** [comment]
Возьму

**Comment by debabin** [comment]
@dacorm подскажи статус

**Comment by dacorm** [comment]
> @dacorm подскажи статус

@debabin надо дописать тесты и демо, постараюсь на неделе допилить, сделаю WIP мр чтобы статус был более явно виден

**Comment by dacorm** [comment]
https://github.com/siberiacancode/reactuse/pull/168

@debabin можешь глянуть, хук такой большой получился, возможно будут пожелания, в МРЕ написал со своей стороны что на этой недел буду дорабатывать

Извиняюсь что затянул, немного туда сюда жизнь появилась))

**Comment by dacorm** [comment]
В идеале хотелось бы услышать замечания по сигнатуре, если они есть, хотя бы с беглого взгляда, и потом я доработаю все по пожеланиям и опишу тесты

**Comment by dacorm** [comment]
@debabin в ближайшее время не смогу допилить, на работе позвали на еще один срочный проект, до конца июля нужно допилить в роли лида играющего, сейчас все время туда уходит, если не ждет, давай передадим кому нибудь
