### ISSUE TITLE
[feat]: Создать хук useRenderInfo

### ISSUE THREAD

**Issue by debabin** [siberiacancode/reactuse#47]

**Comment by GorillaDevq** [comment]
Возьму вот этот 🤓

**Comment by debabin** [comment]
@GorillaDevq подскажи статус

**Comment by GorillaDevq** [comment]
@debabin мой косяк, немного закружился с сессией так, как полгода не был в своей шараге. Сегодня сделаю, примерно к 17-18 по мск приложу пул реквест

**Comment by GorillaDevq** [comment]
#166
