### ISSUE TITLE
[Bug]: На главной странице не отображаются хуки

### ISSUE THREAD

**Issue by GorillaDevq** [siberiacancode/reactuse#52]

**Comment by GorillaDevq** [comment]
@debabin пытаюсь ковырятся с конфигом для vitepress
Я не вижу в файле config.mts, где бы рендерились новые хуки.
То есть условно у нас с кэша берется 4 хука и их как-раз мы видим в превью.
Но как этот кэш создается не могу додуматься...
Тяжело ;(
![image](https://github.com/siberiacancode/reactuse/assets/113595187/bdf60c21-2e18-4d78-a082-27c06ab796af)

**Comment by debabin** [comment]
![image](https://github.com/siberiacancode/reactuse/assets/45297354/52d878c6-a027-4644-b8cd-3c0337bde0a4)
![image](https://github.com/siberiacancode/reactuse/assets/45297354/5b1ee891-e9eb-4e3c-9648-2a06dd1277d8)

Привет, хуки рендерятся здесь, но для features на главной я не нашел возможности рендерить хуки нативно, на самом деле можно их рендерить через vue компонент точно, но через layout нельзя

Я думаю, нужно сделать hook card и просто рендерить массивом их на странице
