### ISSUE TITLE
[style]: Unnecessary explicit import of React

### ISSUE THREAD

**Issue by SergeyKrasnolobov** [siberiacancode/reactuse#54]
Explicit import of React is unnecessary due to babel new jsx transformation mechanic.
https://github.com/reactjs/rfcs/blob/createlement-rfc/text/0000-create-element-changes.md#motivation

To prevent eslint errors just disable `react/jsx-uses-react` and `react/react-in-jsx-scope`

**Comment by debabin** [comment]
Привет, если ли пробела, что я делаю импорт в файлах кода ?

**Comment by SergeyKrasnolobov** [comment]
> Привет, если ли проблема, что я делаю импорт в файлах кода ?

Привет) ну проблем для потребителя конечно не будет, тут скорее наверное хотел обратить внимание на код стайл который команда реакта пушит в своей доке) не знал какой тег прикрепить поэтому оставил as is)

**Comment by debabin** [comment]
Тут еще момент, что жалуется у меня не eslint, а именно ts 

'React' refers to a UMD global, but the current file is a module. Consider adding an import instead.ts(2686)

**Comment by debabin** [comment]
В итоге добавил в ts config https://stackoverflow.com/questions/64656055/react-refers-to-a-umd-global-but-the-current-file-is-a-module и теперь в demo можно не писать import
