### ISSUE TITLE
[doc]: Описать jsdoc для хука useNonInitialEffect

### ISSUE THREAD

**Issue by debabin** [siberiacancode/reactuse#6]
В рамках задачи нужно описать jsdoc по аналогии с готовыми хуками, например useDocumentTitle.

**Comment by wmoooid** [comment]
сделал #56

**Comment by wmoooid** [comment]
@debabin не хочу создавать ишую, спрошу тут:
Может стоит запретить передавать в депсы пустой массив? Ведь получается, что в таком случае эффект ни разу не сработает.

**Comment by debabin** [comment]
@wmoooid я думаю в этом нет смысла, это ответственность юзера
