### ISSUE TITLE
[Bug]: Хук useDocumentTitle

### ISSUE THREAD

**Issue by Dzmitry-Kubarski** [siberiacancode/reactuse#63]
Благодаря дополнительному тест-кейсу (ниже), обнаружил незначительный баг: предположим, что мы пишем без  typescript (да, так вот получилось) и если мы случайно или осознано захотим передать в setTitle что-то отличное от строки, то приложение крашится.

<img width="643" alt="Снимок экрана 2024-05-26 в 14 03 52" src="https://github.com/siberiacancode/reactuse/assets/55586675/8993ae44-9593-4b9c-a191-5365d18c236d">
    
Ошибка происходит в этом месте (ниже, 57 строка), так как мы не проверяем наличие и тип value при попытке вызвать trim().

<img width="605" alt="Снимок экрана 2024-05-26 в 14 07 57" src="https://github.com/siberiacancode/reactuse/assets/55586675/ae7a2e0b-1d6b-49af-84d9-6178f07598a2">

**Comment by Dzmitry-Kubarski** [comment]
> Спасибо за фидбек, можете ли показать ошибку из консоли. Просто лично мое мнение, что такие ошибки на js это норма, а добавлять код гуардами не вижу смысла, ведь в коде будет тоже самое, что-то тип если тип не строка, то выкинь ошибку. Не вижу смысла, но хочу проверить, что ошибка в таком случае информативная

Вот такие ошибки, если передать null или number:
<img width="1433" alt="Снимок экрана 2024-05-26 в 18 55 49" src="https://github.com/siberiacancode/reactuse/assets/55586675/3417a3c6-fcf6-44d1-91c9-a88600de6252">

<img width="1435" alt="Снимок экрана 2024-05-26 в 18 58 52" src="https://github.com/siberiacancode/reactuse/assets/55586675/5c063241-f77c-4115-a2ae-819c83b6cd14">

**Comment by debabin** [comment]
Да я считаю это приземлённой ошибкой, с помощью которой человек легко сможет понять в чем дело
