### ISSUE TITLE
[Bug] Ошибка при использовании хука useLocalStorage с объектом

### ISSUE THREAD

**Issue by VitrivDolkom** [siberiacancode/reactuse#86]
**Описание:**
При прокидывании объекта в дефолтное значение useLocalStorage вылетает ошибка:
![image](https://github.com/siberiacancode/reactuse/assets/71655124/517afbe4-34fe-4f62-ac66-60db534473cd)

Сам объект:
`const defaultUserContextInfo = {
  email: '',
  token: ''
}`

**Окружение:**
- react: 18.2.0
- vite react + ts

**Comment by Dzmitry-Kubarski** [comment]
> const defaultUserContextInfo = { email: '', token: '' }

Вы забыли сделать так - JSON.stringify(defaultUserContextInfo)
