### ISSUE TITLE
[doc]: Описать jsdoc для хука useHover

### ISSUE THREAD

**Issue by debabin** [siberiacancode/reactuse#9]
В рамках задачи нужно описать jsdoc по аналогии с готовыми хуками, например useDocumentTitle.

**Comment by GorillaDevq** [comment]
@debabin Уточняющий вопрос: @typedef нужно писать для этих типов или исключительно для хука?
И момент с @example:
Мы можем в хук передать как и реф элемент с колбэком, так и просто колбэк.
Соответственно из-за этого меняется инициализация хука, и что мы достаем из него.
Поэтому вытекает уточнение, я же верно понимаю, что я использую один раз аннотацию @example и через комментарий разбиваю два варианта использования хука?

Если все верно, я забираю!
![image](https://github.com/siberiacancode/reactuse/assets/113595187/6a7dfacb-c536-4254-b8bd-e93291c8783c)

**Comment by debabin** [comment]
1. Да для типов также описываем коменты
2. Да в example делаем просто вот так

```ts
const result = useHook()
//or
useHooks(params)
```

**Comment by GorillaDevq** [comment]
Заберу
